# Generated by Django 3.1.3 on 2020-11-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201118_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
