# Generated by Django 3.1.3 on 2020-11-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tags',
        ),
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
